deployment:
  tasks:
    - export DEPLOYPATH=/home/focuszez/public_html/app/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R database $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R pages $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH
    - /bin/cp -R storage $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp README.md $DEPLOYPATH