deployment:
  tasks:
    - export DEPLOYPATH=/home/focuszez/public_html/app/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/mkdir -p ${DEPLOYPATH}storage/cache
    - /bin/mkdir -p ${DEPLOYPATH}storage/logs
    - /bin/cp -ru app $DEPLOYPATH
    - /bin/cp -ru config $DEPLOYPATH
    - /bin/cp -ru images $DEPLOYPATH
    - /bin/cp -ru pages $DEPLOYPATH
    - /bin/cp -ru public $DEPLOYPATH
    - /bin/cp -ru routes $DEPLOYPATH
    - /bin/cp -u *.php $DEPLOYPATH
    - /bin/cp -u .htaccess $DEPLOYPATH